
import time

sleeptime = 0.1
start = time.perf_counter()

time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)
time.sleep(sleeptime)


end = time.perf_counter()
diff = end - start - 50 * sleeptime
print(diff)